### ISSUE TITLE
App Name and Domain

### ISSUE THREAD

**Issue by Tumne** [kammanz/raptors-app#106]
ETA: `0.5 days`
---

UPDATE: _June 7th, 2020_:

It has been decided this app will be called "Basketballer Pro" with the domain `basketballerpro.com`

The task is to secure the domain `basketballerpro.com` name on goDaddy. We'll discuss who will own the domain.

https://ca.godaddy.com/domainsearch/find?checkAvail=1&tmskey=&domainToCheck=basketballerpro

---

The issue will be a discussion issue as to the name of the App and domain name. So far these are a few I'm thinking of:

- Hyperballic (hyperballic.com) [$ 0.25 / mo.]
- Hyperballer (hyperballer.com) [$ 0.25 / mo.]
- Basketballer Pro (basketballerpro.com) [$ 0.25 / mo.]
- Hoop Dreamer (hoopdreamer.com) [$ 0.25 / mo.]

I really like `Hype Baller`, however the `.com` would have to be negotiated
- Hype Baller (hypeballer.co) [$ 2.99 / mo.]
- Hype Baller (hypeballer.life) [$ 0.25 / mo.]
- Hype Baller Pro (hypeballerpro.com) [$ 0.25 / mo.] 👍 

You can go on this site to see what names work (remember cheaper the better):

https://ca.godaddy.com/

**Comment by kammanz** [comment]
I like hyperballic and hypeballer. But they sound so exciting. In terms of what I feel represents the app, basketballer pro has a more suitable ring to it.

**Comment by Tumne** [comment]
Agreed, the `Basketballer Pro` has a suitable ring.
thought of another: `Hooper Report`, `Baller Post`

**Comment by Tumne** [comment]
As discussed, I think we are set with `BasketBaller Pro` as the official name and domain. Updating this issue description with a `Deployment` label.
