### ISSUE TITLE
Replace nba endpoint

### ISSUE THREAD

**Issue by Tumne** [kammanz/raptors-app#19]
RIP our last endpoint. stats.nba.com. 👎 

Instead let's use data.nba.net, here is the endpoint for roster:

Info:

team_id: 1610612761
team_code: 'raptors'

Roster:

http://data.nba.net/json/cms/noseason/team/pistons/roster.json

Images

https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/1610612761/2019/260x190/1628384.png

For now this should be fine, but in the future refer to http://nbasense.com/nba-api/ to see other applicable endpoints for this app.

This is a high priority issue.

- [x] Render player list and personal stats with new endpoint
- [x] Render player pics with new endpoint
- [x] Implement select player click handler 
- [x] Render player performance stats on right side 
- [x] Render enlarged player name on right side
- [x] Render enlarged player image on right side
- [x] Clean and refactor code before pushing

**Comment by kammanz** [comment]
Having issue finding a larger image to render on right side after player is selected, as it seems that the api doesn't have one. See notes on pull request.
